### ISSUE TITLE
Why it can't work with pino-pretty when logging to file.

### ISSUE THREAD

**Issue by Plasticine-Yang** [iamolegga/nestjs-pino#1281]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)
- [x] This is not a question about how to use this library with pino-_transport-name-goes-here_

**Question**

It reports following error when I want to log to file with pino-pretty.

```text
[Nest] 22723  - 01/22/2023, 10:43:05 PM     LOG [NestFactory] Starting Nest application...
[Nest] 22723  - 01/22/2023, 10:43:05 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +33ms
[Nest] 22723  - 01/22/2023, 10:43:05 PM   ERROR [ExceptionHandler] () => true could not be cloned.
DataCloneError: () => true could not be cloned.
    at new DOMException (node:internal/per_context/domexception:53:5)
    at new Worker (node:internal/worker:236:17)
    at createWorker (/home/plasticine/code/demos/nest-demo/node_modules/.pnpm/thread-stream@2.3.0/node_modules/thread-stream/index.js:52:18)
    at new ThreadStream (/home/plasticine/code/demos/nest-demo/node_modules/.pnpm/thread-stream@2.3.0/node_modules/thread-stream/index.js:224:19)
    at buildStream (/home/plasticine/code/demos/nest-demo/node_modules/.pnpm/pino@8.8.0/node_modules/pino/lib/transport.js:21:18)
    at transport (/home/plasticine/code/demos/nest-demo/node_modules/.pnpm/pino@8.8.0/node_modules/pino/lib/transport.js:110:10)
    at normalizeArgs (/home/plasticine/code/demos/nest-demo/node_modules/.pnpm/pino@8.8.0/node_modules/pino/lib/tools.js:297:16)
    at pino (/home/plasticine/code/demos/nest-demo/node_modules/.pnpm/pino@8.8.0/node_modules/pino/pino.js:86:28)
    at new PinoLogger (/home/plasticine/code/demos/nest-demo/node_modules/.pnpm/nestjs-pino@3.1.2_sfapocvosrcjidgmqxjuhlo64q/node_modules/nestjs-pino/PinoLogger.js:45:51)
    at Injector.instantiateClass (/home/plasticine/code/demos/nest-demo/node_modules/.pnpm/@nestjs+core@9.2.1_e6la6qvsclaae2becwjnmfvsuq/node_modules/@nestjs/core/injector/injector.js:340:19)
```

The way I use `LoggerModule` in `nestjs-pino`

```TypeScript
@Module({
  imports: [
    LoggerModule.forRoot({
      pinoHttp: {
        transport: {
          target: 'pino-pretty',
          options: {
            destination: new SonicBoom({
              dest: resolve(__dirname, '../dist/logs/log.txt'),
              mkdir: true,
            }),
          } as PrettyOptions,
        },
      },
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

Node.js version: v18.13.0
Operating System: Ubuntu 20.04

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by iamolegga** [comment]
![image](https://user-images.githubusercontent.com/5501657/214032045-31324229-1fac-4894-86e4-6c27d13b3fe2.png)

**Comment by Plasticine-Yang** [comment]
Why closed. I have read and follow the document to config the LoggerModule. It still has error. :(

**Comment by iamolegga** [comment]
This question is not about current library. It's about how to setup pino transport.

https://github.com/pinojs/pino-pretty/issues?q=DataCloneError
