### ISSUE TITLE
[QUESTION] "failed with status code 500" output instead of detailed error message

### ISSUE THREAD

**Issue by shahafa** [iamolegga/nestjs-pino#416]
When I'm throwing an error from Nest application nestjs-pino always prints in the error message "failed with status code 500" even though I'm throwing an error with a detailed message any idea how to solve this?

this is how I setup nestjs-pino
```
    LoggerModule.forRoot({
      pinoHttp: {
        prettyPrint: { colorize: true, translateTime: true },
        serializers: {
          req: (req) => ({
            ...req,
            headers: undefined,
          }),
          res: (res) => ({
            ...res,
            headers: undefined,
          }),
        },
      },
    }),
```

and this is how I throw the error
```
import {InternalServerErrorException} from '@nestjs/common';
throw new InternalServerErrorException("This is my detailed error");
```

And nestjs-pino output
```
   res: {
      "statusCode": 500
    }
    err: {
      "type": "Error",
      "message": "failed with status code 500",
      "stack":
          Error: failed with status code 500
              at ServerResponse.onResFinished (/Users/shahaf/Source/muil/muil/node_modules/pino-http/logger.js:73:38)
              at ServerResponse.clsBind (/Users/shahaf/Source/muil/muil/node_modules/cls-hooked/context.js:172:17)
              at ServerResponse.emit (node:events:388:22)
              at ServerResponse.EventEmitter.emit (node:domain:532:15)
              at ServerResponse.emitted (/Users/shahaf/Source/muil/muil/node_modules/emitter-listener/listener.js:134:21)
              at onFinish (node:_http_outgoing:800:10)
              at callback (node:internal/streams/writable:557:21)
              at afterWrite (node:internal/streams/writable:503:5)
              at afterWriteTick (node:internal/streams/writable:490:10)
              at processTicksAndRejections (node:internal/process/task_queues:79:21)
    }
    responseTime: 94
    req: {
      "id": 1,
      "method": "POST",
      "url": "/api/test/test",
      "remoteAddress": "::1",
      "remotePort": 61221
    }
```

**Comment by gmathavadoss-chwy** [comment]
any update on this issue? I am also facing the same.

**Comment by trycontrolmymind** [comment]
same thing

**Comment by trycontrolmymind** [comment]
This solution works for me:

main.ts
```typescript
const pinoLogger = await app.resolve(PinoLogger);
app.useGlobalFilters(new AllExceptionsFilter(pinoLogger));
```

all-exception.filter.ts
```typescript
export class AllExceptionsFilter implements ExceptionFilter {
  constructor(private readonly logger: PinoLogger) {}
}
```

**Comment by iamolegga** [comment]
solved in v2.0.0

```ts
import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    throw new Error('foo bar baz');
    return this.appService.getHello();
  }
}
```

```sh
{"level":50,"time":1630106183244,"pid":742,"hostname":"my-host","req":{"id":1,"method":"GET","url":"/","query":{},"params":{"0":""},"headers":{"host":"localhost:3000","user-agent":"curl/7.64.1","accept":"*/*"},"remoteAddress":"::1","remotePort":61739},"context":"ExceptionsHandler","msg":"foo bar baz"}
```

**Comment by kasvith** [comment]
@iamolegga cant we get the stack trace there as well?

**Comment by iamolegga** [comment]
@kasvith please open a new feature request for that, will take a look at it when I have time

**Comment by kasvith** [comment]
Done
