### ISSUE TITLE
Cannot use PinoLogger inside of NestJS repository

### ISSUE THREAD

**Issue by ababra** [iamolegga/nestjs-pino#453]
Trying to use PinoLogger inside of a repository as follows (`test-date.repository.ts`):
```typescript
@EntityRepository(TestDate)
export class TestDateRepository extends Repository<TestDate> {
  constructor(private readonly logger: PinoLogger) {
    super();
    this.logger.setContext(TestDateRepository.name);
  }

  async createTestDate(createTestDto: CreateTestDateDto): Promise<TestDate> {
    const { date, venue, expiration } = createTestDto;

    const testDate = new TestDate();
    testDate.date = date;
    testDate.venue = venue;
    testDate.expiration = expiration;
    testDate.active = true;

    try {
      await testDate.save();
      return testDate;
    } catch (error) {
      this.logger.error(
        `Failed to create test date. Data: ${createTestDto}`,
        error.stack,
      );
      throw new InternalServerErrorException();
    }
  }
}
```

However I keep getting the following errors on app startup:
```
[Nest] 16864   - 04/17/2021, 5:39:51 PM   [ExceptionHandler] this.logger.setContext is not a function +2ms
TypeError: this.logger.setContext is not a function
    at new TestDateRepository (/Users/ab/projects/booktest-api/dist/src/test-dates/test-date.repository.js:22:21)
    at EntityManager.getCustomRepository (/Users/ab/projects/booktest-api/node_modules/typeorm/entity-manager/EntityManager.js:692:40)
    at Connection.getCustomRepository (/Users/ab/projects/booktest-api/node_modules/typeorm/connection/Connection.js:389:29)
    at InstanceWrapper.useFactory [as metatype] (/Users/ab/projects/booktest-api/node_modules/@nestjs/typeorm/dist/typeorm.providers.js:12:35)
    at Injector.instantiateClass (/Users/ab/projects/booktest-api/node_modules/@nestjs/core/injector/injector.js:289:55)
    at callback (/Users/ab/projects/booktest-api/node_modules/@nestjs/core/injector/injector.js:42:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Injector.resolveConstructorParams (/Users/ab/projects/booktest-api/node_modules/@nestjs/core/injector/injector.js:114:24)
    at async Injector.loadInstance (/Users/ab/projects/booktest-api/node_modules/@nestjs/core/injector/injector.js:46:9)
    at async Injector.loadProvider (/Users/ab/projects/booktest-api/node_modules/@nestjs/core/injector/injector.js:68:9)
```

Here's my `app.module.ts`:
```typescript
@Module({
  imports: [
    LoggerModule.forRoot({
      pinoHttp: {
        level: process.env.NODE_ENV !== 'production' ? 'debug' : 'info',
        prettyPrint:
          process.env.NODE_ENV !== 'production'
            ? {
                colorize: true,
                levelFirst: true,
                translateTime: 'UTC:mm/dd/yyyy, h:MM:ss TT Z',
              }
            : false,
        redact: ['req.headers.authorization'],
      },
    }),
    TestDatesModule,
  ],
})
export class AppModule {}

```

Thanks for any insights!

**Comment by iamolegga** [comment]
hi, this is not enough, minimal example repo please
