### ISSUE TITLE
[QUESTION] have error while extend pino-logger

### ISSUE THREAD

**Issue by delai** [iamolegga/nestjs-pino#692]
1. logger.service.ts

```
import { Inject, Injectable } from '@nestjs/common'
import { Logger, Params, PARAMS_PROVIDER_TOKEN, PinoLogger } from 'nestjs-pino'
@Injectable()
export class LoggerService extends Logger {
    private aProperty: string
    constructor(
        pinoLogger: PinoLogger,
        @Inject(PARAMS_PROVIDER_TOKEN) params: Params,
        aProperty: string
    ) {
        super(pinoLogger, params)
        this.aProperty = aProperty
    }

    aMethod(): void {
        return
    }
}
```

2. logger.module.ts
```
import { Module } from "@nestjs/common"
import { LoggerModule } from "nestjs-pino"
import { LoggerService } from "./logger.service"

@Module({
  exports: [LoggerService],
  providers: [LoggerService],
  imports: [
    LoggerModule.forRoot({})
  ],
})
export class MyLoggerModule {}
```

3. import the MyLoggerModule in app.module.ts
```
@Module({
  imports: [
    MyLoggerModule
  ],
```

4. while start app, here is the error message
```
[Nest] 8420  - 11/30/2021, 12:29:20 PM     LOG [NestFactory] Starting Nest application...
[Nest] 8420  - 11/30/2021, 12:29:20 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the LoggerService (PinoLogger, pino-params, ?). Please make sure that the argument String at index [2] is available in the MyLoggerModule context.

Potential solutions:
- If String is a provider, is it part of the current MyLoggerModule?
- If String is exported from a separate @Module, is that module imported within MyLoggerModule?
  @Module({
    imports: [ /* the Module containing String */ ]
  })

Error: Nest can't resolve dependencies of the LoggerService (PinoLogger, pino-params, ?). Please make sure that the argument String at index [2] is available in the MyLoggerModule context.

Potential solutions:
- If String is a provider, is it part of the current MyLoggerModule?
- If String is exported from a separate @Module, is that module imported within MyLoggerModule?
  @Module({
    imports: [ /* the Module containing String */ ]
  })

    at Injector.lookupComponentInParentModules (/Users/delai/nest/nest-node/node_modules/@nestjs/core/injector/injector.js:201:19)
    at Injector.resolveComponentInstance (/Users/delai/nest/nest-node/node_modules/@nestjs/core/injector/injector.js:156:33)
    at resolveParam (/Users/delai/nest/nest-node/node_modules/@nestjs/core/injector/injector.js:108:38)
    at async Promise.all (index 2)
    at Injector.resolveConstructorParams (/Users/delai/nest/nest-node/node_modules/@nestjs/core/injector/injector.js:123:27)
    at Injector.loadInstance (/Users/delai/nest/nest-node/node_modules/@nestjs/core/injector/injector.js:52:9)
    at Injector.loadProvider (/Users/delai/nest/nest-node/node_modules/@nestjs/core/injector/injector.js:74:9)
    at async Promise.all (index 3)
    at InstanceLoader.createInstancesOfProviders (/Users/delai/nest/nest-node/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
    at /Users/delai/nest/nest-node/node_modules/@nestjs/core/injector/instance-loader.js:29:13

```

waiting for any suggestion from you

**Comment by iamolegga** [comment]
Not enough data. how are you injecting that extended logger? You can see working examples [here](https://github.com/iamolegga/nestjs-pino/blob/master/__tests__/extending.spec.ts)

But my suggestion is don't extend `Logger`, because this class is made for substitution, the extension support of `Logger` will be dropped in the next major version. So at least you can extend `PinoLogger`.
